#!/usr/bin/env bash

npm version patch --no-git-tag-version
git add package.json package-lock.json

version=$(node -p "require('./package.json').version")

gh-release prepare -t "$version"

c.askContinue "Edit the ChangeLog now, when ready, continue... Ready ?"

gh-release version -t "$version" -m "bump version. Release %s"
gh-release create
